name: Run Scraper Every 5 Hours

on:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js (required for Railway CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate with Railway
        run: echo "${{ secrets.RAILWAY_TOKEN }}" | railway login --ci

      - name: Run Docker container on Railway
        run: railway run --service Scraper_Grad_Project "docker compose run --rm fb-scraper"
