name: Daily Scraper Deploy

on:
  schedule:
    - cron: '0 */5 * * *' #every 5 hours
  workflow_dispatch:     # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login Railway (using token)
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up
